### ISSUE TITLE
sslmode customization

### ISSUE THREAD

**Issue by alcaldj** [Netflix/metaflow-service#336]
New Feature:

Would it be possible to pass postgresql sslmode on the connection string as a parameter? At the moment it is always disabled which avoid connections for Databases where SSL is required. It would be good to pass this as another parameter and allow to switch between disable to required, for example.

Thanks!!

**Comment by saikonen** [comment]
this type of configuration is available since 2.4.4, see the [release notes](https://github.com/Netflix/metaflow-service/releases/tag/v2.4.4)

[2.4.6](https://github.com/Netflix/metaflow-service/releases/tag/v2.4.6) had a related bug fix to migrations so I would start using the feature from that version onward.
